### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by MatMeredith**

### CODE REVIEW

**Comment by MatMeredith** [comment]
Adam: I've pre-emptively merged (as I want to get the builds fixed) but comments welcome.

The issue is that all CentOS RPMs were previously being built using the LICENSE file from clearwater-build-infra (and were therefore always GPL).   

@chris-elford-metaswitch FYI as I think the only place these packages are installed currently is MVSE.   Previously all RPMs picked up the LICENSE file from build-infra.   Now they will get a license file that is the COPYING file in the root of the relevant repo (which will be present and GPL in the PC repos), or a license file which just says "Copyright Metaswitch" if there is no COPYING file -- as will be the case moving forwards for the CC versions of the repos.     I don't know which versions of the repos MVSE currently installs?

**Comment by johadalin** [comment]
If this works and fixes the issue, sounds good to me. 
I did check yesterday, and the RPM packages reported their license correctly in the output of `yum info`, so we were still on the right licenses. However, i think someone on Chris' team should double check that this is all working as expected, just to be sure.

**Comment by MatMeredith** [comment]
@johadalin What do you mean by the RPM packages reported their license correctly?   Which packages?   Presumably they all reported themselves as GPL licensed?   I rather suspect if you look at clearwater-monit it will tell you that it is Copyright Metaswitch, available under the GPL?  (which is not true and I haven't done anything about this yet).

**Comment by chris-elford-metaswitch** [comment]
@johadalin - How do we do that? We're going to need some context on what's going on here to do that checking.

**Pull request merged**
